### PR TITLE
Fix load data on setup

### PR DESCRIPTION
**Pull request by elad-bar**
- Load data from Citymind on setup
- Reduced the payload being sent to Citymind for login
- On WaterConsumptionSensor update, call fetch function to get most updated data from Citymind

### CODE REVIEW

**Comment by maorcc** [comment]
@elad-bar, There are so many good contributions in your pull request, will you be able to finish it, so that it is functional and can be merged?

**Comment by elad-bar** [comment]
@maorcc still haven't got to it yet, promise to get to it soon
Just to be sure, we are talking about support for more than just 1 meter and more documentation, right?

**Comment by maorcc** [comment]
@elad-bar, support for more than one meter is not critical.  There is only one person I know of who wants this feature, and also, this is something that I would know how to add too.

I'd be happy if you first just complete what you started so that it works again.  Remove irrelevant texts (such as "Blue Iris" in comment), etc. And make sure that all this added code is really necessary.

**Comment by elad-bar** [comment]
Cancelling this pull request, restarting from scratch and will create a new pull request

**Pull request closed without merging**
