### PR TITLE
Support UI for component's setup

### PR DESCRIPTION
**Pull request by elad-bar**
Changes:

- Load data from Citymind on setup
- Reduced the payload being sent to Citymind for login
- On WaterConsumptionSensor update, call fetch function to get most updated data from Citymind
- Pre-commit
- Device per water meter
- Integration's option support for changing integration's debug level 
- Password encryption mechnism

### CODE REVIEW

**Review by maorcc — APPROVED** [review]
Excellent!

**Comment by maorcc** [comment]
@elad-bar , you didn't add yourself to codeowners in the manifest.json.  To add you?

**Comment by elad-bar** [comment]
Up to you

**Comment by maorcc** [comment]
Added.

**Comment by maorcc** [comment]
@elad-bar , I've noticed that the icon for the sensors is mdi:eye 
In code, the DEFAULT_ICON = "mdi:alarm-light"
Do you know why the specified icon is not propagating to the UI?

**Comment by elad-bar** [comment]
since the basic sensor (inherits from CityMindEntity) is not using the icon,
It can get removed or we can use it in the future for more accurate icons,
In `managers/entity_manager.py` there are `get_water_last_reading_entity`, `get_water_monthly_consumption_entity` and `get_water_consumption_estimation_entity` the icon propery set to default and it can be changed according to the new icon

**Comment by maorcc** [comment]
In all four 'get' methods the icon property is set to the DEFAULT_ICON, but in the running UI I do not see the default icon anywhere.

**Pull request merged**
